import { BLOCK } from '../engine/world.js';

// util: cor hex -> [r,g,b] 0..1
const C = (hex) => [((hex >> 16) & 255) / 255, ((hex >> 8) & 255) / 255, (hex & 255) / 255];

export const LEVELS = [
  {
    id: 0,
    tag: 'NÍVEL 0',
    name: 'As Salas Amarelas',
    desc: 'Você tropeçou e atravessou o chão da realidade. Papel de parede amarelo, carpete úmido, ' +
      'o zumbido eterno das lâmpadas. Os corredores se repetem — e nas zonas onde a luz morreu, ' +
      'algo sorri para você.',
    objectiveName: 'fusível',
    objectiveNamePlural: 'fusíveis',
    objectiveIcon: '🔌',
    objectiveCount: 4,
    tip: 'Os Sorridentes vivem no escuro e são lentos. Não deixe que encostem em você.',
    size: { x: 80, y: 8, z: 80 },
    gen: 'maze',
    seed: 11,
    fog: { color: 0x4a4014, near: 4, far: 28 },
    ambient: 0x8a7c44,
    ambientIntensity: 1.45,
    playerLight: { color: 0xffe9b0, intensity: 8, distance: 9 },
    palette: {
      [BLOCK.FLOOR]: { c: C(0x6b5f33) },
      [BLOCK.WALL]: { c: C(0xcfc06a) },
      [BLOCK.ACCENT]: { c: C(0xb8a852) },
      [BLOCK.CEIL]: { c: C(0xd8cf9a) },
      [BLOCK.BEDROCK]: { c: C(0x8a7d45) },
      [BLOCK.LIGHT]: { c: C(0xfff8d0), emissive: true },
      [BLOCK.PLACED]: { c: C(0x7a8a5a) },
      [BLOCK.PORTAL]: { c: C(0x101018), emissive: true },
    },
    enemies: [{ type: 'smiler', weight: 1 }],
    maxEnemies: 5,
    spawnInterval: 9,
    initialEnemies: 3,
    weapon: { name: 'Cano de Metal', icon: '🔧', damage: 1, range: 2.8, cooldown: 0.45 },
    waterPickups: 5,
  },
  {
    id: 1,
    tag: 'NÍVEL 1',
    name: 'O Armazém',
    desc: 'Concreto úmido a perder de vista, pilares e caixas abandonadas. A névoa engole a luz das ' +
      'lâmpadas industriais. Aqui a escuridão uiva — e caça em bando.',
    objectiveName: 'chave',
    objectiveNamePlural: 'chaves',
    objectiveIcon: '🗝️',
    objectiveCount: 5,
    tip: 'Os Cães do Vazio são rápidos e atacam juntos. Quebre caixas e erga barricadas.',
    size: { x: 96, y: 10, z: 96 },
    gen: 'warehouse',
    seed: 23,
    fog: { color: 0x1c2024, near: 3, far: 22 },
    ambient: 0x4a5058,
    ambientIntensity: 1.35,
    playerLight: { color: 0xcfe0ff, intensity: 9, distance: 10 },
    palette: {
      [BLOCK.FLOOR]: { c: C(0x50565c) },
      [BLOCK.WALL]: { c: C(0x767e86) },
      [BLOCK.ACCENT]: { c: C(0x5a626b) },
      [BLOCK.CEIL]: { c: C(0x3a4046) },
      [BLOCK.BEDROCK]: { c: C(0x2c3136) },
      [BLOCK.LIGHT]: { c: C(0xd8ecff), emissive: true },
      [BLOCK.PLACED]: { c: C(0x7a8a5a) },
      [BLOCK.PORTAL]: { c: C(0x101018), emissive: true },
      [BLOCK.CRATE]: { c: C(0x9a7a48) },
    },
    enemies: [{ type: 'hound', weight: 1 }],
    maxEnemies: 7,
    spawnInterval: 7,
    initialEnemies: 4,
    weapon: { name: 'Pé de Cabra', icon: '⛏️', damage: 2, range: 2.9, cooldown: 0.42 },
    waterPickups: 6,
  },
  {
    id: 2,
    tag: 'NÍVEL 2',
    name: 'Tubulações',
    desc: 'Túneis de manutenção sem fim, quentes como febre. Vapor assobia nos canos. ' +
      'Nem tudo que parece perdido aqui está realmente parado — algumas silhuetas fingem muito bem.',
    objectiveName: 'válvula',
    objectiveNamePlural: 'válvulas',
    objectiveIcon: '⚙️',
    objectiveCount: 4,
    tip: 'O Ladrão de Pele finge estar inerte até você chegar perto. Ataque primeiro.',
    size: { x: 84, y: 8, z: 84 },
    gen: 'pipes',
    seed: 37,
    fog: { color: 0x201410, near: 2.5, far: 16 },
    ambient: 0x5a4034,
    ambientIntensity: 1.3,
    playerLight: { color: 0xffb070, intensity: 8, distance: 8 },
    palette: {
      [BLOCK.FLOOR]: { c: C(0x4a3a30) },
      [BLOCK.WALL]: { c: C(0x6b5648) },
      [BLOCK.ACCENT]: { c: C(0x7a4a38) },
      [BLOCK.CEIL]: { c: C(0x3a2e26) },
      [BLOCK.BEDROCK]: { c: C(0x2a201a) },
      [BLOCK.LIGHT]: { c: C(0xffc890), emissive: true },
      [BLOCK.PLACED]: { c: C(0x7a8a5a) },
      [BLOCK.PORTAL]: { c: C(0x101018), emissive: true },
      [BLOCK.PIPE]: { c: C(0x8a6a2a) },
    },
    enemies: [{ type: 'skinstealer', weight: 1 }],
    maxEnemies: 6,
    spawnInterval: 8,
    initialEnemies: 4,
    weapon: { name: 'Chave Inglesa Pesada', icon: '🔩', damage: 3, range: 2.8, cooldown: 0.5 },
    waterPickups: 6,
  },
  {
    id: 3,
    tag: 'NÍVEL 3',
    name: 'A Central Elétrica',
    desc: 'Geradores rugem atrás das paredes. Painéis faíscam, e trechos do piso vibram com corrente. ' +
      'Figuras de terno cinza andam pelos corredores — elas não têm rosto, mas sabem onde você está.',
    objectiveName: 'disjuntor',
    objectiveNamePlural: 'disjuntores',
    objectiveIcon: '⚡',
    objectiveCount: 5,
    tip: 'O piso vermelho vibrante eletrocuta. Os Facelings são fortes: use as barricadas.',
    size: { x: 92, y: 9, z: 92 },
    gen: 'plant',
    seed: 53,
    fog: { color: 0x141a20, near: 3, far: 22 },
    ambient: 0x5c6c7a,
    ambientIntensity: 1.5,
    playerLight: { color: 0xd0e8ff, intensity: 9, distance: 9 },
    palette: {
      [BLOCK.FLOOR]: { c: C(0x3c4248) },
      [BLOCK.WALL]: { c: C(0x5a6670) },
      [BLOCK.ACCENT]: { c: C(0x4a5866) },
      [BLOCK.CEIL]: { c: C(0x2c3238) },
      [BLOCK.BEDROCK]: { c: C(0x22262a) },
      [BLOCK.LIGHT]: { c: C(0xcfe8ff), emissive: true },
      [BLOCK.PLACED]: { c: C(0x7a8a5a) },
      [BLOCK.PORTAL]: { c: C(0x101018), emissive: true },
      [BLOCK.HAZARD]: { c: C(0xff5030), emissive: true },
      [BLOCK.PIPE]: { c: C(0x30506a) },
    },
    enemies: [{ type: 'faceling', weight: 1 }],
    maxEnemies: 6,
    spawnInterval: 8,
    initialEnemies: 4,
    weapon: { name: 'Machado de Incêndio', icon: '🪓', damage: 4, range: 3.0, cooldown: 0.48 },
    waterPickups: 7,
  },
  {
    id: 4,
    tag: 'NÍVEL !',
    name: 'A Fuga',
    desc: 'Uma arena vermelha onde a realidade sangra. No centro, o GUARDIÃO DO VAZIO — o carcereiro ' +
      'de tudo que já se perdeu aqui. Derrote-o e a última porta se abre. Falhe, e você vira parede.',
    objectiveName: 'guardião',
    objectiveNamePlural: 'guardiões',
    objectiveIcon: '💀',
    objectiveCount: 1,
    boss: true,
    tip: 'Desvie da investida do Guardião e ataque logo depois. Ele chama Sorridentes quando ferido.',
    size: { x: 64, y: 12, z: 64 },
    gen: 'arena',
    seed: 66,
    fog: { color: 0x2a0808, near: 4, far: 30 },
    ambient: 0x6a2a2a,
    ambientIntensity: 1.35,
    playerLight: { color: 0xffd0b0, intensity: 9, distance: 10 },
    palette: {
      [BLOCK.FLOOR]: { c: C(0x4a2020) },
      [BLOCK.WALL]: { c: C(0x6b2e2e) },
      [BLOCK.ACCENT]: { c: C(0x8a3a3a) },
      [BLOCK.CEIL]: { c: C(0x301414) },
      [BLOCK.BEDROCK]: { c: C(0x241010) },
      [BLOCK.LIGHT]: { c: C(0xff8060), emissive: true },
      [BLOCK.PLACED]: { c: C(0x7a8a5a) },
      [BLOCK.PORTAL]: { c: C(0x101018), emissive: true },
    },
    enemies: [{ type: 'smiler', weight: 1 }],
    maxEnemies: 3,          // lacaios invocados pelo chefe
    spawnInterval: 999,     // sem spawn automático: só o chefe invoca
    initialEnemies: 0,
    weapon: { name: 'Machado do Êxodo', icon: '🪓', damage: 5, range: 3.1, cooldown: 0.45 },
    waterPickups: 8,
  },
];
